### PR TITLE
This branch will add the queuexml schema and related files.

### PR DESCRIPTION
**Pull request by somexpert**

### CODE REVIEW

**Comment by somexpert** [comment]
@vphill, @ldko, @damonkelley, an example instance of the xml doc was included with the issue. It is shown below. So, are any fields going to be optional, or will they all be mandatory? Also, what exactly are the `<start/>` and `<end/>` elements?

**Comment by somexpert** [comment]
```
    <queueEntry xmlns="http://something.com/coda/queuexml/">
        <ark>ark:/67531/someid</ark>
        <oxum>104305328.6</oxum>
        <urlListLink>http://server.com/bag/ark:/67531/someid.urls</urlListLink>
        <status>1</status>
        <start/>
        <end/>
        <position>1</position>
    </queueEntry>
```

**Comment by ldko** [comment]
`start` and `end` are for the harvest start and end datetimes. This has to do with Coda replication. The harvester is run on our storage server, it gets the next queue entry from the Django coda_replication app, starts replication processing, then PUTs back the queue entry to the app with a status of 2 and start time when replication for the item begins. When replication is complete, there is a PUT with the final status that also updates the end time.

**Comment by somexpert** [comment]
so then not all entries in the queue will have those times, correct?

**Comment by ldko** [comment]
there will sometimes not be a value for those times.

**Comment by somexpert** [comment]
Well in that case there are several approaches to consider (since the dateTime type does not accept an empty string):
1. We create a new datatype that allows either a datetime or nothing
2. We make the elements optional and do not allow empty instances
3. We allow empty instances of the elements but require them to have an attribute that shows them to be empty (nill attribute)
4. We don't do any type checking and just make those elements accept any string

**Comment by ldko** [comment]
I think 2. will be okay. We _should_ just need to change the coda_replication app to not write the empty `<start/>` and `<end/>` tags. I don't think we have anything client-side sending empty start/end tags or expecting they will absolutely be in the XML. `<position>` should be optional because when POSTing a new queue entry, the client is unaware of what the position should be. `<status>` _could_ also be optional because I think we just assign a `status` of 1 to anything that is POSTed anyway.

**Comment by somexpert** [comment]
@vphill, @ldko, @damonkelley, this schema (and readme and example doc) are ready for review.

**Comment by damonkelley** [comment]
Looks good to me. I am going to defer to @vphill and @ldko though.

**Comment by ldko** [comment]
After looking at this again, I think we should change `<status>` to required. Other than that, I think it is fine.

**Comment by somexpert** [comment]
`<status>` is now required

**Comment by ldko** [comment]
:+1:

**Comment by vphill** [comment]
:+1:

**Pull request merged**
