### PR TITLE
Json schema

### LINKED ISSUE #3: Make root README non-XML specific
Since it turns out this repo will include non-XML schemas too, we need to make the top level README more generic.

### PR DESCRIPTION
**Pull request by somexpert**
Adds the json schema and example. Also fixes both the local and root READMEs. Should fix #3.

### CODE REVIEW

**Comment by somexpert** [comment]
@ldko, @damonkelley, what do you guys think about the way the JSON schema is done? By that I mean the lack of a root element actually called unixFileOutput.

**Comment by somexpert** [comment]
BTW, [this](http://www.jsonschemavalidator.net/) is a good website if you guys want to check anything out functionally.

**Comment by damonkelley** [comment]
LGTM

**Comment by ldko** [comment]
Any thoughts on adding a `title` of "unixFileOutput" and/or a `description` something like "A representation of output from the Unix file program"?

**Comment by somexpert** [comment]
My thoughts are that I like those suggestions. I'll add them now.

**Comment by ldko** [comment]
:+1:

**Pull request merged**
